SELECT
    *
FROM
    STUDENT
WHERE
    EXISTS (
    SELECT
        *
    FROM
        UNIVERSITY
    WHERE
        STUDENT.CITY = UNIVERSITY.CITY
        AND STUDENT.UNIVERSITY_ID <> UNIVERSITY.UNIVERSITY_ID);
