SELECT
    STUDENT.SURNAME, UNIVERSITY.RATING
FROM
    STUDENT
        INNER JOIN
            UNIVERSITY
                ON
                    STUDENT.UNIV_ID = UNIVERSITY.UNIV_ID
ORDER BY
    STUDENT.SURNAME;
